# Generated by Django 5.1.7 on 2025-03-18 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="phone",
            name="stock",
            field=models.IntegerField(default=0),
        ),
    ]
