# Generated by Django 5.1.7 on 2025-03-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0005_laptop"),
    ]

    operations = [
        migrations.CreateModel(
            name="Watch",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("name", models.CharField(max_length=100)),
                ("case_color", models.CharField(max_length=50)),
                ("strap_color", models.CharField(max_length=50)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stock", models.IntegerField(default=0)),
            ],
        ),
    ]
